//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderShopItem = new HashSet<OrderShopItem>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string ShipAddress { get; set; }
        public bool Proceed { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
    
        public virtual ICollection<OrderShopItem> OrderShopItem { get; set; }
    }
}
